Mobile first 2
donice/Microverse-Portfolio pull request #2
Opened 2023-07-06 10:34 UTC by donice

In this PR, I:
- Completed the mobile-first task
- Imported  neccesary images into the image folder
- Styled in it css

2023-07-06 21:19 UTC, Alusp requested changes
Hi @donice, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![close](https://media.giphy.com/media/nJKDTpuxnZE7fb6Z1b/giphy.gif)

 ## Highlights

- [x] Linters set-up ✔️
- [x] Commit messages descriptive ✔️
- [ ] Professional Github Flow used ✔️
- [ ] Professional PR Summary Flow used ✔️
- [ ] Work section UI is great ✔️


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 21:19 UTC, Alusp commented on style.css
`.project {`
  `display: inline-flex;`
  `padding: 114px 24px;`
  `flex-direction: column;`
  `align-items: center;`
  `gap: 88px;`
}`

- [ ] Good job so far :clap: , However, according to the project requirement you are supposed to set the project section properties to `display:grid` instead of `display: inline-flex`, Please fix it :slightly_smiling_face:

2023-07-06 21:19 UTC, Alusp commented on index.html
> +        </h1>
- [ ] For HTML semantics, and accessibilities and according to the project requirement, you are supposed to use only one `h1` tag in your entire HTML file, Please replace this to `h2` instead. :slightly_smiling_face:

2023-07-06 21:19 UTC, Alusp commented on index.html
> +        <span class="purple">LET'S CONNECT</span>
- [ ] For HTML semantics, and accessibilities and according to the project requirement, you are supposed to wrap your `LET'S CONNECT` with an `h2` or `h3` tag, Please fix it :slightly_smiling_face:

2023-07-06 21:19 UTC, Alusp commented on index.html
`<div class="skill-container">`
            `<span>HTML</span>`
           ` <span>CSS</span>`
            `<span>Javascript</span>`
          `</div>`

- [ ] As part of the project requirement, you are suppose to use `ul` tag for the `class="skill-container"` instead of `<div>` and wrap `HTML`, `CSS`, `Javascript` with `li` tags, Please resolve it. :slightly_smiling_face:

2023-07-06 21:19 UTC, Alusp commented on index.html
> +      </div>
- [ ] As part of the project requirement, you are suppose to use `ul` and `li` for categories in "About myself" section. Languages, Frameworks, and Skills should be list items, Please resolve it. :slightly_smiling_face:

2023-07-07 13:28 UTC, donice commented on index.html
> +        <span class="purple">LET'S CONNECT</span>
@Alusp This wasn't a requirement

2023-07-07 15:09 UTC, Munsa1 requested changes
Hi @donice, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Made Most Requested Changes :heavy_check_mark: 
Responsive Design :heavy_check_mark: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
### Important 🔴 
- [ ] Going forward, kindly use the imperative tense for your commit messages and not the past tense.
e.g
`Fix the styles linter error` ✔️ 
`
not 

  `Fixed the styles linter error` ❌ 


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 15:09 UTC, Munsa1 commented on index.html
> +        </div>
- [ ] As requested by the previous reviewer, Please use ul and li for categories in the "About myself" section. Languages, Frameworks, and Skills should be list items. Kindly resolve this.
Note that the container with the class name `drop` should be a `ul` tag and each of the categories, Languages, Frameworks, and Skills should be wrapped as list items (`li`) tags.

Screenshot of [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md)
![image](https://github.com/donice/Microverse-Portfolio/assets/81932478/572bb436-0367-43fa-95a8-65c349ebcbbc)

2023-07-07 16:33 UTC, TuyishimireEric approved these changes
# Status: APPROVED 🟢  
### Hi  @donice    👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉

## Highlights
✔ Made suggested changes 👍 
✔ Descriptive Pull Request title and summary. 👍  
✔ Good use of GitHub flow 👍 
### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 17:36 UTC, merged